### PR TITLE
Add join page

### PR DESCRIPTION
**Pull request by edmundmiller**
Moved some stuff around. I'd like to make it pop a little bit more and direct people's eyes of wear to look like https://nf-co.re/join

Creating the PR looking for feedback!

### CODE REVIEW

**Comment by jakobnissen** [comment]
Thanks for doing this.
I think it would be nice to have a short "contact" section on the main page, perhaps just pointing to Discourse and Slack. At least to me, if I had any questions about using BioJulia as a user, I might not look for contact info in the "Join us" page in the sidebar.

**Comment by kescobo** [comment]
Build errors here and #21 appear to be problems with permissions. There's probably some secret thing that we can add to the build configuration, but for now I'm just going to add @Emiller88 to the repo with write permission and run them again.

**Comment by kescobo** [comment]
Hmm, maybe not. @tlienart would you mind taking a look? https://github.com/BioJulia/biojulia.github.io/actions/runs/5828128326/job/15821241791?pr=20#step:4:478

**Comment by tlienart** [comment]
the issue is something to do with tokens [some notes here from 2020 on the github-pages-action repo](https://github.com/JamesIves/github-pages-deploy-action/issues/308); given that this PR: https://github.com/BioJulia/biojulia.github.io/actions/runs/5833801346 worked fine, can you try just merging stuff and seeing if it works?

What might happen is that the *preview* path is faulty (e.g. it tries to do something with a non-existing branch, I'd need to check) but the rest works fine.

**Comment by kescobo** [comment]
Yeah, I can build it locally, and clearly it works on merging. I also works if the branch originates from this repo (eg https://github.com/BioJulia/biojulia.github.io/pull/17#issuecomment-1668049888). 

But it would be awesome to have a way for external collaborators to make contributions w/o write permissions and still get build previews. [Feature request] because you obviously don't have enough on your plate :laughing:

**Comment by tlienart** [comment]
No it's good to know that the preview path doesn't work properly, GitHub actions are very powerful but I'm still a beginner when it comes to those so im not surprised there are issues; definitely something to look into as your use case is one that I'd expect many people to have (eg the Julia website folks..)

**Comment by edmundmiller** [comment]
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
> When a workflow is triggered by the [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event, the GITHUB_TOKEN is granted read/write repository permission, even when it is triggered from a public fork. For more information, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)."

> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does.

Let's see if this works

**Comment by edmundmiller** [comment]
Partial success. It runs, but still no preview URL 😞

**Comment by kescobo** [comment]
:thinking: well, that's a kind of progress...

**Comment by tlienart** [comment]
what may have happened is that on the last trigger the build action saw "no change" so that there was effectively "nothing new to commit". Could I suggest maybe trying to re-trigger with a dummy commit where you change a word or a `.` or something?

(I need to do some more thorough investigation of this preview path with external contributors but I don't really have the time atm to dig through that... sorry)

**Comment by edmundmiller** [comment]
Have we confirmed that it works from a non-fork branch as well?

**Comment by kescobo** [comment]
Let's find out: https://github.com/BioJulia/biojulia.github.io/pull/24

**Comment by kescobo** [comment]
Nope :-( https://github.com/BioJulia/biojulia.github.io/actions/runs/5857819238/job/15880512464

**Comment by edmundmiller** [comment]
Cool, that's progress! Let's follow up in #23, and we can focus on the join page here now.

**Comment by edmundmiller** [comment]
It's a start, if there's any outstanding issues let me know and we can either address before merging this or follow up in another PR!

**Comment by kescobo** [comment]
@Emiller88 Can you resolve the conflict here? I can't remember which edit on the header came first / is preferred. I'm not picky

**Comment by edmundmiller** [comment]
Done!

**Pull request merged**
